services:
  gridvis:
    image: jnza/gridvis-service:nightly-m
    volumes:
      - ./GridVisProjects:/opt/GridVisProjects
      - ./GridVisData:/opt/GridVisData
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=GridVis
      - DB_USER=root
      - DB_PASSWORD=rootPWD
    depends_on:
      - database
  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootPWD