services:
  gridvis:
    image: jnza/gridvis-service:nightly-m
    shm_size: "1gb"
    volumes:
      - ./GridVisProjects:/opt/GridVisProjects
      - ./GridVisData:/opt/GridVisData
    ports:
      - 8080:8080
    environment:
      - GRIDVIS_ADMIN_PASSWORD=${GRIDVIS_ADMIN_PASSWORD:?set GRIDVIS_ADMIN_PASSWORD}
      - PROJECT_NAME=GridVisProject
      - AUTO_SYNC=true
