name: Docker Image CI Beta Release

env:
  GV_BASE_IMAGE: GV_BASE_IMAGE=beta-beta

on:
  push:
    branches: [ beta ]
    tags:
      - 'v*'
  pull_request:
    branches: [ beta ]
  workflow_dispatch:
  schedule:
    - cron: "23 21 * * 1-5"  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: jnza/gridvis-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            suffix=-beta
      -
        name: Docker meta
        id: meta_m
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: jnza/gridvis-service
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            suffix=-beta-m,onlatest=true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: maintenance
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_m.outputs.tags }}
          labels: ${{ steps.meta_m.outputs.labels }}
          build-args: ${{ env.GV_BASE_IMAGE }}
